# This is a generated file. Not intended for manual editing.
services:
  azurewebapptest:
    build:
      context: "C:\\pedro\\projetos_novos\\azuretests"
      dockerfile: "C:\\pedro\\projetos_novos\\azuretests\\AzureWebAppTest\\Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/AzureWebAppTest.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "azurewebapptest:dev"
    ports: []
    volumes:
    - "C:\\pedro\\projetos_novos\\azuretests\\AzureWebAppTest:/app:rw"
    - "C:\\pedro\\projetos_novos\\azuretests:/src:rw"
    - "C:\\Users\\Aline Santos\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
